"""init

Revision ID: faa0edde2390
Revises: 
Create Date: 2024-08-17 17:29:29.541444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa0edde2390'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catagory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('cata_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cata_id'], ['catagory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_cata_id'), 'site', ['cata_id'], unique=False)
    op.create_table('page',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('cata_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cata_id'], ['catagory.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_cata_id'), 'page', ['cata_id'], unique=False)
    op.create_index(op.f('ix_page_site_id'), 'page', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_site_id'), table_name='page')
    op.drop_index(op.f('ix_page_cata_id'), table_name='page')
    op.drop_table('page')
    op.drop_index(op.f('ix_site_cata_id'), table_name='site')
    op.drop_table('site')
    op.drop_table('catagory')
    # ### end Alembic commands ###
