"""add delete mark to site

Revision ID: acdd61a2d114
Revises: 373484736456
Create Date: 2024-11-08 16:35:36.500582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acdd61a2d114'
down_revision: Union[str, None] = '373484736456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('disabled', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'disabled')
    # ### end Alembic commands ###
