"""add time to page and icon to site

Revision ID: b66d7f2288d1
Revises: cd28825c6282
Create Date: 2024-08-25 21:10:31.500312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66d7f2288d1'
down_revision: Union[str, None] = 'cd28825c6282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('publish_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('site', sa.Column('icon', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'icon')
    op.drop_column('page', 'publish_time')
    # ### end Alembic commands ###
