"""add column subject to keyword

Revision ID: 373484736456
Revises: de4435c33f04
Create Date: 2024-11-07 08:33:13.585667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373484736456'
down_revision: Union[str, None] = 'de4435c33f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('subject', sa.Text(), server_default='unspecified', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword', 'subject')
    # ### end Alembic commands ###
