"""add logo and background for group

Revision ID: 2134a3659ff0
Revises: 74331fc05e32
Create Date: 2025-04-14 14:27:20.950802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2134a3659ff0'
down_revision: Union[str, None] = '74331fc05e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('logo', sa.String(length=2048), nullable=True))
    op.add_column('group', sa.Column('background', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'background')
    op.drop_column('group', 'logo')
    # ### end Alembic commands ###
