"""alter unique of page to two column

Revision ID: 7095510f807d
Revises: b33009a996d8
Create Date: 2025-11-02 20:35:03.046794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7095510f807d'
down_revision: Union[str, None] = 'b33009a996d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('page_source_url_key', 'page', type_='unique')
    op.create_unique_constraint('uix_source_url_site_id', 'page', ['source_url', 'site_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_source_url_site_id', 'page', type_='unique')
    op.create_unique_constraint('page_source_url_key', 'page', ['source_url'])
    # ### end Alembic commands ###
