"""add table subject as set of keywords

Revision ID: 413555197e2e
Revises: 2134a3659ff0
Create Date: 2025-04-14 15:35:01.339475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "413555197e2e"
down_revision: Union[str, None] = "2134a3659ff0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subject",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subject_group_id"), "subject", ["group_id"], unique=False)
    op.create_table(
        "subject_keyword_relation",
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keyword.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
        ),
        sa.PrimaryKeyConstraint("subject_id", "keyword_id"),
    )
    conn = op.get_bind()
    # first, create the subject table, with the keyword.subject as name
    conn.execute(
        sa.text(
            """
            INSERT INTO subject (name, group_id)
                SELECT DISTINCT subject, 1
                FROM keyword
                WHERE subject IS NOT NULL AND subject != ''
            """
        )
    )
    # second, link the subject to the keyword
    conn.execute(
        sa.text(
            """
            INSERT INTO subject_keyword_relation (subject_id, keyword_id)
                SELECT subject.id, keyword.id
                FROM keyword
                JOIN subject ON subject.name = keyword.subject
            """
        )
    )
    op.drop_column("keyword", "subject")
    ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "keyword",
        sa.Column(
            "subject",
            sa.TEXT(),
            server_default=sa.text("'unspecified'::text"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # update keyword.subject with the first subject name linked to the keyword
    # use a single sql
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """UPDATE keyword SET subject = 
                (
                    SELECT name FROM subject_keyword_relation JOIN subject
                    ON subject.id = subject_keyword_relation.subject_id
                    WHERE keyword.id = subject_keyword_relation.keyword_id LIMIT 1
                )
                WHERE id IN (SELECT keyword_id FROM subject_keyword_relation)
                """
        )
    )
    op.drop_table("subject_keyword_relation")
    op.drop_index(op.f("ix_subject_group_id"), table_name="subject")
    op.drop_table("subject")
    # ### end Alembic commands ###
