"""allow empty ja_code

Revision ID: bec3d46ff0be
Revises: cb3aa3b3cfbc
Create Date: 2025-03-21 23:54:11.441803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec3d46ff0be'
down_revision: Union[str, None] = 'cb3aa3b3cfbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'jaccount_code',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'jaccount_code',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
