"""add sort key into category and subject

Revision ID: f8465673fbee
Revises: 76d729db41a2
Create Date: 2025-04-23 14:07:22.543074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8465673fbee'
down_revision: Union[str, None] = '76d729db41a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('sort_key', sa.Integer(), server_default='0', nullable=False))
    op.add_column('subject', sa.Column('sort_key', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'sort_key')
    op.drop_column('category', 'sort_key')
    # ### end Alembic commands ###
