"""add the connection between category and site

Revision ID: 074cd00a697e
Revises: 551d337c979c
Create Date: 2025-03-29 21:22:41.332055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074cd00a697e'
down_revision: Union[str, None] = '551d337c979c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('belonged_group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_category_belonged_group_id'), 'category', ['belonged_group_id'], unique=False)
    op.create_foreign_key(None, 'category', 'group', ['belonged_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_index(op.f('ix_category_belonged_group_id'), table_name='category')
    op.drop_column('category', 'belonged_group_id')
    # ### end Alembic commands ###
