"""add subject_id into category as a hint

Revision ID: 548b3ab0bc90
Revises: 3809e1ab83a7
Create Date: 2025-05-09 11:25:29.150275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548b3ab0bc90'
down_revision: Union[str, None] = '3809e1ab83a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_category_subject_id'), 'category', ['subject_id'], unique=False)
    op.create_foreign_key(op.f('category_subject_id_fkey'), 'category', 'subject', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('category_subject_id_fkey'), 'category', type_='foreignkey')
    op.drop_index(op.f('ix_category_subject_id'), table_name='category')
    op.drop_column('category', 'subject_id')
    # ### end Alembic commands ###
