"""add Group of User

Revision ID: cb3aa3b3cfbc
Revises: 064e21fbfed9
Create Date: 2025-03-20 00:26:49.891514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3aa3b3cfbc'
down_revision: Union[str, None] = '064e21fbfed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'site', ['url'])
    op.add_column('user', sa.Column('group_id', sa.Integer(), nullable=True))
    op.alter_column('user', 'userType',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'organization',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_user_group_id'), 'user', ['group_id'], unique=False)
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_group_id'), table_name='user')
    op.alter_column('user', 'organization',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'userType',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('user', 'group_id')
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_table('group')
    # ### end Alembic commands ###
