"""add default show behavior for group

Revision ID: 02c831baafb4
Revises: 599196dec8ac
Create Date: 2025-04-14 20:26:41.536619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c831baafb4'
down_revision: Union[str, None] = '599196dec8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('sidebar_show_mode', sa.Text(), server_default='category', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'sidebar_show_mode')
    # ### end Alembic commands ###
