"""add cneas to user

Revision ID: 76d729db41a2
Revises: 02c831baafb4
Create Date: 2025-04-16 15:12:11.313017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d729db41a2'
down_revision: Union[str, None] = '02c831baafb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cnaes_code', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('user_cnaes_code_key'), 'user', ['cnaes_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_cnaes_code_key'), 'user', type_='unique')
    op.drop_column('user', 'cnaes_code')
    # ### end Alembic commands ###
