"""remove relation between page and category

Revision ID: 6cd7a00bd435
Revises: 3c066a782f63
Create Date: 2025-04-08 10:59:48.543257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd7a00bd435'
down_revision: Union[str, None] = '3c066a782f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_cate_id', table_name='page')
    op.drop_constraint('page_cate_id_fkey', 'page', type_='foreignkey')
    op.drop_column('page', 'cate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('cate_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('page_cate_id_fkey', 'page', 'category', ['cate_id'], ['id'])
    op.create_index('ix_page_cate_id', 'page', ['cate_id'], unique=False)
    # ### end Alembic commands ###
