"""rename category.group_id

Revision ID: 3809e1ab83a7
Revises: f8465673fbee
Create Date: 2025-04-23 14:56:44.947288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3809e1ab83a7'
down_revision: Union[str, None] = 'f8465673fbee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'belonged_group_id', new_column_name='group_id')
    op.drop_index('ix_category_belonged_group_id', table_name='category')
    op.create_index(op.f('ix_category_group_id'), 'category', ['group_id'], unique=False)
    op.drop_constraint('category_belonged_group_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(op.f('category_group_id_fkey'), 'category', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'group_id', new_column_name='belonged_group_id')
    op.drop_constraint(op.f('category_group_id_fkey'), 'category', type_='foreignkey')
    op.create_foreign_key('category_belonged_group_id_fkey', 'category', 'group', ['belonged_group_id'], ['id'])
    op.drop_index(op.f('ix_category_group_id'), table_name='category')
    op.create_index('ix_category_belonged_group_id', 'category', ['belonged_group_id'], unique=False)
    # ### end Alembic commands ###
