"""add more attr to page

Revision ID: 626849b7a577
Revises: 548b3ab0bc90
Create Date: 2025-05-23 15:51:18.683131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626849b7a577'
down_revision: Union[str, None] = '548b3ab0bc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('title_cn', sa.String(length=128), nullable=True))
    op.add_column('page', sa.Column('full_content_cn', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'full_content_cn')
    op.drop_column('page', 'title_cn')
    # ### end Alembic commands ###
