"""allow subscribe site into arbitary category

Revision ID: 74331fc05e32
Revises: 6cd7a00bd435
Create Date: 2025-04-13 16:44:38.637202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74331fc05e32'
down_revision: Union[str, None] = '6cd7a00bd435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_site_relation', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('user_site_relation', sa.Column('negative', sa.Boolean(), server_default='0', nullable=False))
    op.create_foreign_key(None, 'user_site_relation', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_site_relation', type_='foreignkey')
    op.drop_column('user_site_relation', 'negative')
    op.drop_column('user_site_relation', 'category_id')
    # ### end Alembic commands ###
