"""add user-in-group status

Revision ID: 515f4de5bb2f
Revises: bec3d46ff0be
Create Date: 2025-03-22 00:01:18.443867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515f4de5bb2f'
down_revision: Union[str, None] = 'bec3d46ff0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group_accepted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('group_admin', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'group_admin')
    op.drop_column('user', 'group_accepted')
    # ### end Alembic commands ###
