"""make relation (category,site) to many to many

Revision ID: 3c066a782f63
Revises: 074cd00a697e
Create Date: 2025-03-29 21:26:46.393828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c066a782f63'
down_revision: Union[str, None] = '074cd00a697e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_site_relation',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'site_id')
    )
    # for every site, construct relation with new table
    op.execute('INSERT INTO category_site_relation (category_id, site_id) SELECT cate_id, id FROM site')
    # drop cate_id from site table
    op.drop_index('ix_site_cate_id', table_name='site')
    op.drop_constraint('site_cate_id_fkey', 'site', type_='foreignkey')
    op.drop_column('site', 'cate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('cate_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('site_cate_id_fkey', 'site', 'category', ['cate_id'], ['id'])
    op.create_index('ix_site_cate_id', 'site', ['cate_id'], unique=False)

    # set the cate_id with the minimum category id who is related to the site
    op.execute('UPDATE site SET cate_id = (SELECT MIN(category.id) FROM category_site_relation WHERE category_site_relation.site_id = site.id)')
    # drop the relation table
    op.drop_table('category_site_relation')
    # ### end Alembic commands ###
