// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from '@hey-api/client-fetch';
import type { LoginData, LoginResponse, LoginError, LogoutData, LogoutResponse, GetUserStatusData, GetUserStatusResponse, RegisterData, RegisterResponse, RegisterError, Redirect2OauthData, Redirect2OauthError, DoAuthCallbackData, DoAuthCallbackError, GetGroupsData, GetGroupsResponse, GetPendingMembersData, GetPendingMembersResponse, GetPendingMembersError, RemoveUserFromGroupData, RemoveUserFromGroupResponse, RemoveUserFromGroupError, GetGroupUsersData, GetGroupUsersResponse, GetGroupUsersError, AddUserToGroupData, AddUserToGroupResponse, AddUserToGroupError, LeaveGroupData, LeaveGroupResponse, GetUserinfoNotInGroupData, GetUserinfoNotInGroupResponse, GetUserinfoNotInGroupError, GetPagesData, GetPagesResponse, GetPagesError, GetSitesData, GetSitesResponse, AddSiteData, AddSiteResponse, AddSiteError, GetSiteData, GetSiteResponse, GetSiteError, GetPageData, GetPageResponse, GetPageError, UnsubscribeData, UnsubscribeResponse, UnsubscribeError, GetSubscribeData, GetSubscribeResponse, SubscribeData, SubscribeResponse, SubscribeError, DeleteKeywordData, DeleteKeywordResponse, DeleteKeywordError, GetKeywordData, GetKeywordResponse, GetKeywordError, AddKeywordData, AddKeywordResponse, AddKeywordError, GetCategoriesData, GetCategoriesResponse, AddCategoryData, AddCategoryResponse, AddCategoryError, GetCategoryData, GetCategoryResponse, GetCategoryError, RemoveSiteFromCategoryData, RemoveSiteFromCategoryResponse, RemoveSiteFromCategoryError, AddSiteToCategoryData, AddSiteToCategoryResponse, AddSiteToCategoryError, GetSubjectsData, GetSubjectsResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginResponse, LoginError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/login',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<LogoutResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/logout',
        ...options
    });
};

/**
 * Get User Status
 */
export const getUserStatus = <ThrowOnError extends boolean = false>(options?: Options<GetUserStatusData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUserStatusResponse, unknown, ThrowOnError>({
        url: '/user/status',
        ...options
    });
};

/**
 * Register
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterResponse, RegisterError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/register',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Redirect2Oauth
 */
export const redirect2Oauth = <ThrowOnError extends boolean = false>(options: Options<Redirect2OauthData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, Redirect2OauthError, ThrowOnError>({
        url: '/login/oauth/{provider}',
        ...options
    });
};

/**
 * Do Auth Callback
 */
export const doAuthCallback = <ThrowOnError extends boolean = false>(options: Options<DoAuthCallbackData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, DoAuthCallbackError, ThrowOnError>({
        url: '/auth/{provider}',
        ...options
    });
};

/**
 * Get Groups
 */
export const getGroups = <ThrowOnError extends boolean = false>(options?: Options<GetGroupsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetGroupsResponse, unknown, ThrowOnError>({
        url: '/group',
        ...options
    });
};

/**
 * Get Pending Members
 */
export const getPendingMembers = <ThrowOnError extends boolean = false>(options?: Options<GetPendingMembersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetPendingMembersResponse, GetPendingMembersError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/group/members/pending',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Remove User From Group
 */
export const removeUserFromGroup = <ThrowOnError extends boolean = false>(options: Options<RemoveUserFromGroupData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<RemoveUserFromGroupResponse, RemoveUserFromGroupError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/group/members',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Group Users
 */
export const getGroupUsers = <ThrowOnError extends boolean = false>(options?: Options<GetGroupUsersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetGroupUsersResponse, GetGroupUsersError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/group/members',
        ...options
    });
};

/**
 * Add User To Group
 */
export const addUserToGroup = <ThrowOnError extends boolean = false>(options: Options<AddUserToGroupData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddUserToGroupResponse, AddUserToGroupError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/group/members',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Leave Group
 */
export const leaveGroup = <ThrowOnError extends boolean = false>(options?: Options<LeaveGroupData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<LeaveGroupResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/group/leave',
        ...options
    });
};

/**
 * Get Userinfo Not In Group
 */
export const getUserinfoNotInGroup = <ThrowOnError extends boolean = false>(options: Options<GetUserinfoNotInGroupData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetUserinfoNotInGroupResponse, GetUserinfoNotInGroupError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/free',
        ...options
    });
};

/**
 * Get Pages
 */
export const getPages = <ThrowOnError extends boolean = false>(options: Options<GetPagesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetPagesResponse, GetPagesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/pages',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Sites
 */
export const getSites = <ThrowOnError extends boolean = false>(options?: Options<GetSitesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSitesResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/site',
        ...options
    });
};

/**
 * Add Site
 */
export const addSite = <ThrowOnError extends boolean = false>(options: Options<AddSiteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddSiteResponse, AddSiteError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/site',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Site
 */
export const getSite = <ThrowOnError extends boolean = false>(options: Options<GetSiteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSiteResponse, GetSiteError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/site/{site_id}',
        ...options
    });
};

/**
 * Get Page
 */
export const getPage = <ThrowOnError extends boolean = false>(options: Options<GetPageData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPageResponse, GetPageError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/page/{page_id}',
        ...options
    });
};

/**
 * Unsubscribe
 */
export const unsubscribe = <ThrowOnError extends boolean = false>(options: Options<UnsubscribeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<UnsubscribeResponse, UnsubscribeError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/subscribe',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Subscribe
 */
export const getSubscribe = <ThrowOnError extends boolean = false>(options?: Options<GetSubscribeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSubscribeResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/subscribe',
        ...options
    });
};

/**
 * Subscribe
 */
export const subscribe = <ThrowOnError extends boolean = false>(options: Options<SubscribeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SubscribeResponse, SubscribeError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/subscribe',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Keyword
 */
export const deleteKeyword = <ThrowOnError extends boolean = false>(options: Options<DeleteKeywordData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteKeywordResponse, DeleteKeywordError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/keyword',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Keyword
 */
export const getKeyword = <ThrowOnError extends boolean = false>(options?: Options<GetKeywordData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetKeywordResponse, GetKeywordError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/keyword',
        ...options
    });
};

/**
 * Add Keyword
 */
export const addKeyword = <ThrowOnError extends boolean = false>(options: Options<AddKeywordData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddKeywordResponse, AddKeywordError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/keyword',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Categories
 */
export const getCategories = <ThrowOnError extends boolean = false>(options?: Options<GetCategoriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCategoriesResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/category',
        ...options
    });
};

/**
 * Add Category
 */
export const addCategory = <ThrowOnError extends boolean = false>(options: Options<AddCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddCategoryResponse, AddCategoryError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/category',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Category
 */
export const getCategory = <ThrowOnError extends boolean = false>(options: Options<GetCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCategoryResponse, GetCategoryError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/category/{cate_id}',
        ...options
    });
};

/**
 * Remove Site From Category
 */
export const removeSiteFromCategory = <ThrowOnError extends boolean = false>(options: Options<RemoveSiteFromCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<RemoveSiteFromCategoryResponse, RemoveSiteFromCategoryError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/category/site',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Add Site To Category
 */
export const addSiteToCategory = <ThrowOnError extends boolean = false>(options: Options<AddSiteToCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddSiteToCategoryResponse, AddSiteToCategoryError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/category/site',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Subjects
 */
export const getSubjects = <ThrowOnError extends boolean = false>(options?: Options<GetSubjectsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSubjectsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/subjects',
        ...options
    });
};