// This file is auto-generated by @hey-api/openapi-ts

export type BodyAddKeyword = {
    words: Array<string>;
    add_for_user: boolean;
    keep_user_existed: boolean;
};

export type BodyAddSiteToCategory = {
    cate_id: number;
    site_id: number;
};

export type BodyAddUserToGroup = {
    user_id: number;
    group_id?: number | null;
};

export type BodyDeleteKeyword = {
    keyword_id: number;
};

export type BodyGetPendingMembers = {
    group_id?: number | null;
};

export type BodyLogin = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type BodyRemoveSiteFromCategory = {
    cate_id: number;
    site_id: number;
};

export type BodyRemoveUserFromGroup = {
    user_id: number;
};

export type BodySubscribe = {
    sites_id: Array<number>;
    keep_user_existed: boolean;
};

export type Category = {
    id?: number | null;
    name: string;
    readonly sites: Array<SiteItem>;
};

export type CategoryItem = {
    id?: number | null;
    name: string;
};

export type Group = {
    id: number;
    name: string;
    logo?: string | null;
    background?: string | null;
    sidebar_show_mode?: 'category' | 'subject';
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Keyword = {
    id: number;
    word: string;
};

export type LoginStatus = {
    is_login: boolean;
    user?: User | null;
};

export type OperationMsg = {
    status?: number;
    message?: string;
};

export type Page = {
    site_id: number;
    site: string;
    site_icon: string | null;
    id: number;
    source_url: string;
    title: string;
    content: string;
    publish_time: string;
    score: number;
    keywords: Array<Keyword>;
    full_content: string;
};

export type PageGet = {
    site?: number | null;
    today?: boolean;
    bookmarked?: boolean;
    filter_user_keyword?: boolean;
    subscribe?: number;
    category?: number | Array<number> | null;
    subject?: number | Array<number> | null;
    time_start?: string | null;
    time_end?: string | null;
    search_title?: string | null;
    search_content?: string | null;
    count?: number;
    cursor_id?: number;
    /**
     * get count pages for each site and concat without further sort
     */
    count_for_each_site?: boolean;
    sort?: SortType;
};

export type PageItem = {
    site_id: number;
    site: string;
    site_icon: string | null;
    id: number;
    source_url: string;
    title: string;
    content: string;
    publish_time: string;
    score: number;
    keywords: Array<Keyword>;
};

export type PagedQueryPageItem = {
    cursor_id?: number | null;
    has_next?: boolean;
    data?: Array<PageItem>;
};

export type RegisterForm = {
    username: string;
    password: string;
    name: string;
    group_id?: number | null;
};

export type SessionToken = {
    access_token: string;
    token_type: 'Bearer';
};

export type Site = {
    id?: number | null;
    name: string;
    url: string | Array<string> | null;
    icon?: string | null;
};

export type SiteItem = {
    id?: number | null;
    name: string;
    url: string | Array<string> | null;
    icon?: string | null;
};

export type SortType = 'time' | 'score';

export type Subject = {
    id: number;
    name: string;
    keywords: Array<Keyword>;
};

export type User = {
    id: number;
    name: string;
    username: string;
    jaccount_code?: string | null;
    userType?: string | null;
    organization?: string | null;
    is_admin?: boolean;
    avatars?: string | null;
    group?: Group | null;
    group_accepted?: boolean;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: SessionToken;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetUserStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/status';
};

export type GetUserStatusResponses = {
    /**
     * Successful Response
     */
    200: LoginStatus;
};

export type GetUserStatusResponse = GetUserStatusResponses[keyof GetUserStatusResponses];

export type RegisterData = {
    body: RegisterForm;
    path?: never;
    query?: never;
    url: '/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type Redirect2OauthData = {
    body?: never;
    path: {
        provider: string;
    };
    query: {
        state: string;
    };
    url: '/login/oauth/{provider}';
};

export type Redirect2OauthErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type Redirect2OauthError = Redirect2OauthErrors[keyof Redirect2OauthErrors];

export type Redirect2OauthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DoAuthCallbackData = {
    body?: never;
    path: {
        provider: string;
    };
    query: {
        code: string;
        state: string;
    };
    url: '/auth/{provider}';
};

export type DoAuthCallbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DoAuthCallbackError = DoAuthCallbackErrors[keyof DoAuthCallbackErrors];

export type DoAuthCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/group';
};

export type GetGroupsResponses = {
    /**
     * Successful Response
     */
    200: Array<Group>;
};

export type GetGroupsResponse = GetGroupsResponses[keyof GetGroupsResponses];

export type GetPendingMembersData = {
    body?: BodyGetPendingMembers;
    path?: never;
    query?: never;
    url: '/group/members/pending';
};

export type GetPendingMembersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPendingMembersError = GetPendingMembersErrors[keyof GetPendingMembersErrors];

export type GetPendingMembersResponses = {
    /**
     * Successful Response
     */
    200: Array<User>;
};

export type GetPendingMembersResponse = GetPendingMembersResponses[keyof GetPendingMembersResponses];

export type RemoveUserFromGroupData = {
    body: BodyRemoveUserFromGroup;
    path?: never;
    query?: never;
    url: '/group/members';
};

export type RemoveUserFromGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveUserFromGroupError = RemoveUserFromGroupErrors[keyof RemoveUserFromGroupErrors];

export type RemoveUserFromGroupResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type RemoveUserFromGroupResponse = RemoveUserFromGroupResponses[keyof RemoveUserFromGroupResponses];

export type GetGroupUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * only effects when user is admin.
         */
        group_id?: number | null;
    };
    url: '/group/members';
};

export type GetGroupUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGroupUsersError = GetGroupUsersErrors[keyof GetGroupUsersErrors];

export type GetGroupUsersResponses = {
    /**
     * Successful Response
     */
    200: Array<User>;
};

export type GetGroupUsersResponse = GetGroupUsersResponses[keyof GetGroupUsersResponses];

export type AddUserToGroupData = {
    body: BodyAddUserToGroup;
    path?: never;
    query?: never;
    url: '/group/members';
};

export type AddUserToGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddUserToGroupError = AddUserToGroupErrors[keyof AddUserToGroupErrors];

export type AddUserToGroupResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type AddUserToGroupResponse = AddUserToGroupResponses[keyof AddUserToGroupResponses];

export type LeaveGroupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/group/leave';
};

export type LeaveGroupResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type LeaveGroupResponse = LeaveGroupResponses[keyof LeaveGroupResponses];

export type GetUserinfoNotInGroupData = {
    body?: never;
    path?: never;
    query: {
        username: string;
    };
    url: '/user/free';
};

export type GetUserinfoNotInGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserinfoNotInGroupError = GetUserinfoNotInGroupErrors[keyof GetUserinfoNotInGroupErrors];

export type GetUserinfoNotInGroupResponses = {
    /**
     * Successful Response
     */
    200: User | null;
};

export type GetUserinfoNotInGroupResponse = GetUserinfoNotInGroupResponses[keyof GetUserinfoNotInGroupResponses];

export type GetPagesData = {
    body: PageGet;
    path?: never;
    query?: never;
    url: '/pages';
};

export type GetPagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPagesError = GetPagesErrors[keyof GetPagesErrors];

export type GetPagesResponses = {
    /**
     * Successful Response
     */
    200: PagedQueryPageItem;
};

export type GetPagesResponse = GetPagesResponses[keyof GetPagesResponses];

export type GetSitesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/site';
};

export type GetSitesResponses = {
    /**
     * Successful Response
     */
    200: Array<SiteItem>;
};

export type GetSitesResponse = GetSitesResponses[keyof GetSitesResponses];

export type AddSiteData = {
    body: SiteItem;
    path?: never;
    query?: never;
    url: '/site';
};

export type AddSiteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddSiteError = AddSiteErrors[keyof AddSiteErrors];

export type AddSiteResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type AddSiteResponse = AddSiteResponses[keyof AddSiteResponses];

export type GetSiteData = {
    body?: never;
    path: {
        site_id: number;
    };
    query?: never;
    url: '/site/{site_id}';
};

export type GetSiteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSiteError = GetSiteErrors[keyof GetSiteErrors];

export type GetSiteResponses = {
    /**
     * Successful Response
     */
    200: Site;
};

export type GetSiteResponse = GetSiteResponses[keyof GetSiteResponses];

export type GetPageData = {
    body?: never;
    path: {
        page_id: number;
    };
    query?: never;
    url: '/page/{page_id}';
};

export type GetPageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageError = GetPageErrors[keyof GetPageErrors];

export type GetPageResponses = {
    /**
     * Successful Response
     */
    200: Page;
};

export type GetPageResponse = GetPageResponses[keyof GetPageResponses];

export type UnsubscribeData = {
    body: number;
    path?: never;
    query?: never;
    url: '/subscribe';
};

export type UnsubscribeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnsubscribeError = UnsubscribeErrors[keyof UnsubscribeErrors];

export type UnsubscribeResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type UnsubscribeResponse = UnsubscribeResponses[keyof UnsubscribeResponses];

export type GetSubscribeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subscribe';
};

export type GetSubscribeResponses = {
    /**
     * Successful Response
     */
    200: Array<SiteItem>;
};

export type GetSubscribeResponse = GetSubscribeResponses[keyof GetSubscribeResponses];

export type SubscribeData = {
    body: BodySubscribe;
    path?: never;
    query?: never;
    url: '/subscribe';
};

export type SubscribeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscribeError = SubscribeErrors[keyof SubscribeErrors];

export type SubscribeResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type SubscribeResponse = SubscribeResponses[keyof SubscribeResponses];

export type DeleteKeywordData = {
    body: BodyDeleteKeyword;
    path?: never;
    query?: never;
    url: '/keyword';
};

export type DeleteKeywordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteKeywordError = DeleteKeywordErrors[keyof DeleteKeywordErrors];

export type DeleteKeywordResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type DeleteKeywordResponse = DeleteKeywordResponses[keyof DeleteKeywordResponses];

export type GetKeywordData = {
    body?: never;
    path?: never;
    query?: {
        personal?: boolean;
    };
    url: '/keyword';
};

export type GetKeywordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetKeywordError = GetKeywordErrors[keyof GetKeywordErrors];

export type GetKeywordResponses = {
    /**
     * Successful Response
     */
    200: Array<Keyword>;
};

export type GetKeywordResponse = GetKeywordResponses[keyof GetKeywordResponses];

export type AddKeywordData = {
    body: BodyAddKeyword;
    path?: never;
    query?: never;
    url: '/keyword';
};

export type AddKeywordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddKeywordError = AddKeywordErrors[keyof AddKeywordErrors];

export type AddKeywordResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type AddKeywordResponse = AddKeywordResponses[keyof AddKeywordResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/category';
};

export type GetCategoriesResponses = {
    /**
     * Successful Response
     */
    200: Array<Category>;
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type AddCategoryData = {
    body: CategoryItem;
    path?: never;
    query?: never;
    url: '/category';
};

export type AddCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddCategoryError = AddCategoryErrors[keyof AddCategoryErrors];

export type AddCategoryResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type AddCategoryResponse = AddCategoryResponses[keyof AddCategoryResponses];

export type GetCategoryData = {
    body?: never;
    path: {
        cate_id: number;
    };
    query?: never;
    url: '/category/{cate_id}';
};

export type GetCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCategoryError = GetCategoryErrors[keyof GetCategoryErrors];

export type GetCategoryResponses = {
    /**
     * Successful Response
     */
    200: Category;
};

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses];

export type RemoveSiteFromCategoryData = {
    body: BodyRemoveSiteFromCategory;
    path?: never;
    query?: never;
    url: '/category/site';
};

export type RemoveSiteFromCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveSiteFromCategoryError = RemoveSiteFromCategoryErrors[keyof RemoveSiteFromCategoryErrors];

export type RemoveSiteFromCategoryResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type RemoveSiteFromCategoryResponse = RemoveSiteFromCategoryResponses[keyof RemoveSiteFromCategoryResponses];

export type AddSiteToCategoryData = {
    body: BodyAddSiteToCategory;
    path?: never;
    query?: never;
    url: '/category/site';
};

export type AddSiteToCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddSiteToCategoryError = AddSiteToCategoryErrors[keyof AddSiteToCategoryErrors];

export type AddSiteToCategoryResponses = {
    /**
     * Successful Response
     */
    200: OperationMsg;
};

export type AddSiteToCategoryResponse = AddSiteToCategoryResponses[keyof AddSiteToCategoryResponses];

export type GetSubjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subjects';
};

export type GetSubjectsResponses = {
    /**
     * Successful Response
     */
    200: Array<Subject>;
};

export type GetSubjectsResponse = GetSubjectsResponses[keyof GetSubjectsResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};