from common.models import Keyword
from server.db import SqlSession

keywords = [
    Keyword(word="班会", subject="标题"),
    Keyword(word="主题团日", subject="标题"),
    Keyword(word="主题党日", subject="标题"),
    Keyword(word="系列活动", subject="标题"),
    Keyword(word="交流", subject="标题"),
    Keyword(word="学生座谈", subject="标题"),
    Keyword(word="分享", subject="标题"),
    Keyword(word="展示", subject="标题"),
    Keyword(word="游园活动", subject="标题"),
    Keyword(word="党员教育", subject="标题"),
    Keyword(word="团员教育", subject="标题"),
    Keyword(word="入学教育", subject="标题"),
    Keyword(word="毕业教育", subject="标题"),
    Keyword(word="实践活动", subject="标题"),
    Keyword(word="主题宣讲", subject="标题"),
    Keyword(word="大学生讲思政", subject="标题"),
    Keyword(word="学生榜样", subject="标题"),
    Keyword(word="体育文化", subject="标题"),
    Keyword(word="劳动文化", subject="标题"),
    Keyword(word="艺术文化", subject="标题"),
    Keyword(word="训练", subject="标题"),
    Keyword(word="学生骨干", subject="标题"),
    Keyword(word="微党", subject="标题"),
    Keyword(word="爱心市集", subject="标题"),
    Keyword(word="心理健康", subject="标题"),
    Keyword(word="志愿服务", subject="标题"),
    Keyword(word="劳动教育", subject="标题"),
    Keyword(word="校园下午", subject="标题"),
    Keyword(word="青春歌会", subject="标题"),
    Keyword(word="职业生涯", subject="标题"),
    Keyword(word="校园", subject="标题"),
    Keyword(word="进校", subject="标题"),
    Keyword(word="第一", subject="标题"),
    Keyword(word="一站式学生社", subject="标题"),
    Keyword(word="学工部", subject="主办单位"),
    Keyword(word="学生工作部", subject="主办单位"),
    Keyword(word="学生处", subject="主办单位"),
    Keyword(word="研工部", subject="主办单位"),
    Keyword(word="研究生工作部", subject="主办单位"),
    Keyword(word="校团委", subject="主办单位"),
    Keyword(word="武装部", subject="主办单位"),
    Keyword(word="大学生活动中心", subject="主办单位"),
    Keyword(word="心理中心", subject="主办单位"),
    Keyword(word="就业中心", subject="主办单位"),
    Keyword(word="学生会", subject="主办单位"),
    Keyword(word="研究生会", subject="主办单位"),
    Keyword(word="学生社区", subject="主办单位"),
    Keyword(word="就业", subject="活动主题"),
    Keyword(word="心理", subject="活动主题"),
    Keyword(word="劳动", subject="活动主题"),
    Keyword(word="社会实践", subject="活动主题"),
    Keyword(word="资助", subject="活动主题"),
    Keyword(word="少数民族", subject="活动主题"),
    Keyword(word="志愿", subject="活动主题"),
    Keyword(word="学雷锋", subject="活动主题"),
    Keyword(word="学生党员", subject="活动主题"),
    Keyword(word="新生入学", subject="活动主题"),
    Keyword(word="军训", subject="活动主题"),
    Keyword(word="国防教育", subject="活动主题"),
    Keyword(word="研究生支教团", subject="活动主题"),
    Keyword(word="共建", subject="活动主题"),
    Keyword(word="面对面", subject="活动主题"),
    Keyword(word="嘉年华", subject="活动主题"),
    Keyword(word="风采", subject="活动主题"),
    Keyword(word="辅导员素质能力", subject="活动主题"),
    Keyword(word="生涯规划", subject="活动主题"),
    Keyword(word="演讲比赛", subject="活动主题"),
    Keyword(word="训练营", subject="活动主题"),
    Keyword(word="全校师生", subject="参与对象"),
    Keyword(word="辅导员", subject="参与对象"),
    Keyword(word="各级师生", subject="参与对象"),
    Keyword(word="本硕博学生", subject="参与对象"),
    Keyword(word="新生", subject="参与对象"),
    Keyword(word="毕业生", subject="参与对象"),
    Keyword(word="宣讲团", subject="参与对象"),
    Keyword(word="实践团", subject="参与对象"),
    Keyword(word="志愿者", subject="参与对象"),
    Keyword(word="教育", subject="情况通报"),
    Keyword(word="高等教育", subject="情况通报"),
    Keyword(word="科技人才", subject="情况通报"),
    Keyword(word="高校", subject="情况通报"),
    Keyword(word="大学", subject="情况通报"),
    Keyword(word="本科生", subject="情况通报"),
    Keyword(word="研究生", subject="情况通报"),
    Keyword(word="博士", subject="情况通报"),
    Keyword(word="学科交叉", subject="情况通报"),
    Keyword(word="创新就业", subject="情况通报"),
    Keyword(word="立德树人", subject="情况通报"),
    Keyword(word="科教融汇", subject="情况通报"),
    Keyword(word="产教融合", subject="情况通报"),
    Keyword(word="成果转化", subject="情况通报"),
    Keyword(word="合作", subject="情况通报"),
    Keyword(word="揭牌", subject="情况通报"),
    Keyword(word="成立", subject="情况通报"),
]

with SqlSession() as db:
    for keyword in keywords:
        db.add(keyword)
    db.commit()
