/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElNo: typeof import('element-plus/es')['ElNo']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}
